In [1]:
import pandas as pd

In [2]:
d = pd.read_csv('heart.csv')

In [4]:
d['age']=d['age']/365

In [5]:
print(d['age'])

0        50.391781
1        55.419178
2        51.663014
3        48.282192
4        47.873973
           ...
69995    52.712329
69996    61.920548
69997    52.235616
69998    61.454795
69999    56.273973
Name: age, Length: 70000, dtype: float64

In [6]:
print(d.shape)

(70000, 12)

In [7]:
print(d.columns)

Index(['age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol',
       'gluc', 'smoke', 'alco', 'active', 'cardio'],
      dtype='object')

In [9]:
d.rename(columns={
    'active':'phy_activity',
},inplace=True)

In [10]:
print(d.columns)

Index(['age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol',
       'gluc', 'smoke', 'alco', 'phy_activity', 'cardio'],
      dtype='object')

In [11]:
d.columns = d.columns.str.upper()

In [12]:
print(d.columns)

Index(['AGE', 'GENDER', 'HEIGHT', 'WEIGHT', 'AP_HI', 'AP_LO', 'CHOLESTEROL',
       'GLUC', 'SMOKE', 'ALCO', 'PHY_ACTIVITY', 'CARDIO'],
      dtype='object')

In [13]:
print(d.head())

         AGE  GENDER  HEIGHT  WEIGHT  AP_HI  AP_LO  CHOLESTEROL  GLUC  SMOKE  \
0  50.391781       2     168    62.0    110     80            1     1      0
1  55.419178       1     156    85.0    140     90            3     1      0
2  51.663014       1     165    64.0    130     70            3     1      0
3  48.282192       2     169    82.0    150    100            1     1      0
4  47.873973       1     156    56.0    100     60            1     1      0

   ALCO  PHY_ACTIVITY  CARDIO
0     0             1       0
1     0             1       1
2     0             0       1
3     0             1       1
4     0             0       0

In [15]:
print(d.isnull().sum())

AGE             0
GENDER          0
HEIGHT          0
WEIGHT          0
AP_HI           0
AP_LO           0
CHOLESTEROL     0
GLUC            0
SMOKE           0
ALCO            0
PHY_ACTIVITY    0
CARDIO          0
dtype: int64

In [16]:
print(d.duplicated().sum())

24

In [22]:
a = d[d.duplicated(keep=False)]
print(a)

             AGE  GENDER  HEIGHT  WEIGHT  AP_HI  AP_LO  CHOLESTEROL  GLUC  \
1142   47.926027       2     169    74.0    120     80            1     1
1204   46.008219       1     165    68.0    120     80            1     1
1568   60.123288       1     165    60.0    120     80            1     1
1612   55.597260       1     162    70.0    110     70            1     1
2305   56.150685       1     165    70.0    120     80            1     1
2677   60.484932       1     175    69.0    120     80            1     1
6325   39.868493       1     158    64.0    120     80            1     1
8190   59.665753       1     160    58.0    120     80            1     1
10494  46.402740       2     170    70.0    120     80            1     1
10562  56.150685       1     165    70.0    120     80            1     1
10777  52.021918       1     164    65.0    120     80            1     1
16333  54.405479       1     165    68.0    120     80            1     1
17101  44.273973       1     168    65.0    120     80            1     1
17168  58.164384       1     164    62.0    120     80            1     1
20040  52.216438       1     165    65.0    120     80            1     1
21784  46.008219       1     165    68.0    120     80            1     1
21871  58.301370       1     165    65.0    120     80            1     1
22694  50.282192       1     169    67.0    120     80            1     1
24356  56.208219       1     164    66.0    120     80            1     1
28300  46.041096       1     157    67.0    120     80            1     1
28997  49.890411       1     160    60.0    120     80            1     1
32683  48.041096       2     165    65.0    120     80            1     1
38505  52.021918       1     164    65.0    120     80            1     1
38589  57.860274       1     160    60.0    120     80            1     1
40301  60.117808       1     165    65.0    120     80            1     1
40365  39.868493       1     158    64.0    120     80            1     1
42450  50.282192       1     169    67.0    120     80            1     1
44653  46.402740       2     170    70.0    120     80            1     1
45125  58.301370       1     165    65.0    120     80            1     1
45748  60.484932       1     175    69.0    120     80            1     1
45810  58.164384       1     164    62.0    120     80            1     1
47733  51.997260       1     165    65.0    120     80            1     1
48917  60.123288       1     165    60.0    120     80            1     1
50432  47.926027       2     169    74.0    120     80            1     1
52552  60.117808       1     165    65.0    120     80            1     1
54716  51.931507       1     165    75.0    120     80            1     1
56643  48.041096       2     165    65.0    120     80            1     1
56906  55.597260       1     162    70.0    110     70            1     1
57946  51.931507       1     165    75.0    120     80            1     1
58730  54.405479       1     165    68.0    120     80            1     1
60453  56.208219       1     164    66.0    120     80            1     1
60474  46.041096       1     157    67.0    120     80            1     1
62318  51.997260       1     165    65.0    120     80            1     1
64169  44.273973       1     168    65.0    120     80            1     1
65079  49.890411       1     160    60.0    120     80            1     1
65622  59.665753       1     160    58.0    120     80            1     1
66190  52.216438       1     165    65.0    120     80            1     1
68281  57.860274       1     160    60.0    120     80            1     1

       SMOKE  ALCO  PHY_ACTIVITY  CARDIO
1142       0     0             1       1
1204       0     0             1       0
1568       0     0             1       0
1612       0     0             1       0
2305       0     0             1       0
2677       0     0             1       1
6325       0     0             1       0
8190       0     0             1       0
10494      0     0             0       0
10562      0     0             1       0
10777      0     0             1       0
16333      0     0             1       0
17101      0     0             1       1
17168      0     0             1       0
20040      0     0             1       1
21784      0     0             1       0
21871      0     0             1       0
22694      0     0             1       0
24356      0     0             0       0
28300      0     0             1       0
28997      0     0             1       0
32683      0     0             1       0
38505      0     0             1       0
38589      0     0             0       1
40301      0     0             1       1
40365      0     0             1       0
42450      0     0             1       0
44653      0     0             0       0
45125      0     0             1       0
45748      0     0             1       1
45810      0     0             1       0
47733      0     0             0       0
48917      0     0             1       0
50432      0     0             1       1
52552      0     0             1       1
54716      0     0             1       1
56643      0     0             1       0
56906      0     0             1       0
57946      0     0             1       1
58730      0     0             1       0
60453      0     0             0       0
60474      0     0             1       0
62318      0     0             0       0
64169      0     0             1       1
65079      0     0             1       0
65622      0     0             1       0
66190      0     0             1       1
68281      0     0             0       1

In [24]:
print(a.nunique()) #prints unique

AGE             24
GENDER           2
HEIGHT          10
WEIGHT          12
AP_HI            2
AP_LO            2
CHOLESTEROL      1
GLUC             1
SMOKE            1
ALCO             1
PHY_ACTIVITY     2
CARDIO           2
dtype: int64

In [29]:
d['CARDIO'].value_counts()

CARDIO
0    35021
1    34979
Name: count, dtype: int64

In [30]:
d['AGE'].value_counts()

AGE
54.084932    32
49.961644    32
56.005479    31
55.824658    31
50.008219    31
             ..
47.235616     1
44.046575     1
53.241096     1
60.446575     1
58.769863     1
Name: count, Length: 8076, dtype: int64

In [31]:
d['GENDER'].value_counts()

GENDER
1    45530
2    24470
Name: count, dtype: int64

In [36]:
d.columns = d.columns.str.lower()

In [37]:
print(d.columns)

Index(['age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol',
       'gluc', 'smoke', 'alco', 'phy_activity', 'cardio'],
      dtype='object')

In [40]:
d[['ap_hi','ap_lo']].describe()

              ap_hi         ap_lo
count  70000.000000  70000.000000
mean     128.817286     96.630414
std      154.011419    188.472530
min     -150.000000    -70.000000
25%      120.000000     80.000000
50%      120.000000     80.000000
75%      140.000000     90.000000
max    16020.000000  11000.000000

In [41]:
'''d = d[(d['ap_hi'] > 50) & (d['ap_hi'] < 250)]
d = d[(d['ap_lo'] > 30) & (d['ap_lo'] < 150)]


Rows with ❌ negative values → removed
Rows with ❌ very high values → removed
Rows with ❌ ap_hi ≤ ap_lo → removed

d = d[d['ap_hi'] > d['ap_lo']] #Systolic > Diastolic (always)'''

In [43]:
d[['ap_hi','ap_lo']].describe()

              ap_hi         ap_lo
count  68665.000000  68665.000000
mean     126.666715     81.298886
std       16.678923      9.417035
min       60.000000     40.000000
25%      120.000000     80.000000
50%      120.000000     80.000000
75%      140.000000     90.000000
max      240.000000    140.000000

In [46]:
print(d.shape)
d.describe()

(68665, 12)

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,phy_activity,cardio
count,68665.000000,68665.000000,68665.00000,68665.000000,68665.000000,68665.000000,68665.000000,68665.000000,68665.000000,68665.000000,68665.000000,68665.000000
mean,53.327234,1.348620,164.36065,74.117986,126.666715,81.298886,1.364611,1.225690,0.087978,0.053361,0.803350,0.494677
std,6.762144,0.476537,8.18382,14.332117,16.678923,9.417035,0.678857,0.571563,0.283265,0.224753,0.397469,0.499975
min,29.583562,1.000000,55.00000,11.000000,60.000000,40.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,48.375342,1.000000,159.00000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,53.975342,1.000000,165.00000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,58.421918,2.000000,170.00000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,64.967123,2.000000,250.00000,200.000000,240.000000,140.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [47]:
d = d[(d['height'] > 120) & (d['height'] < 220)]
'''Normal adult range ≈ 140 cm – 200 cm
Extreme but possible:
Min ≈ 120 cm
Max ≈ 220 cm'''
d = d[(d['weight'] > 30) & (d['weight'] < 150)]
'''Typical adults: 40 – 120 kg
Extreme cases:
Min ≈ 30 kg
Max ≈ 150 kg'''

In [49]:
d = d[(d['ap_hi'] > 80) & (d['ap_hi'] < 200)]
d = d[(d['ap_lo'] > 50) & (d['ap_lo'] < 120)]
'''Systolic (ap_hi)
Normal: ~120
Safe range: 90 – 180
Diastolic (ap_lo)
Normal: ~80
Safe range: 60 – 120'''
d = d[d['ap_hi'] > d['ap_lo']]

In [50]:
print(d.shape)
d.describe()

(68087, 12)

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,phy_activity,cardio
count,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000
mean,53.328960,1.348378,164.440451,74.008391,126.452069,81.193811,1.363153,1.224889,0.087755,0.053138,0.803457,0.493486
std,6.761301,0.476460,7.840451,14.005436,16.074694,9.031674,0.677964,0.570867,0.282941,0.224310,0.397386,0.499961
min,29.583562,1.000000,125.000000,31.000000,85.000000,52.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,48.382192,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,53.978082,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,58.424658,2.000000,170.000000,82.000000,140.000000,90.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,64.967123,2.000000,207.000000,149.000000,197.000000,119.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [52]:
70000-68087

1913

In [55]:
print(d.shape)
d.describe()

(68087, 12)

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,phy_activity,cardio
count,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000,68087.000000
mean,53.328960,1.348378,164.440451,74.008391,126.452069,81.193811,1.363153,1.224889,0.087755,0.053138,0.803457,0.493486
std,6.761301,0.476460,7.840451,14.005436,16.074694,9.031674,0.677964,0.570867,0.282941,0.224310,0.397386,0.499961
min,29.583562,1.000000,125.000000,31.000000,85.000000,52.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,48.382192,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,53.978082,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,58.424658,2.000000,170.000000,82.000000,140.000000,90.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,64.967123,2.000000,207.000000,149.000000,197.000000,119.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [56]:
d[d['ap_hi'] < d['ap_lo']]

Empty DataFrame
Columns: [age, gender, height, weight, ap_hi, ap_lo, cholesterol, gluc, smoke, alco, phy_activity, cardio]
Index: []

In [58]:
d['cardio'].value_counts()

cardio
0    34487
1    33600
Name: count, dtype: int64

In [59]:
#d['bmi'] = d['weight'] / ((d['height']/100) ** 2)

In [65]:
d.drop(columns=['bmi'], inplace=True)

In [66]:
print(d)

             age  gender  height  weight  ap_hi  ap_lo  cholesterol  gluc  \
0      50.391781       2     168    62.0    110     80            1     1
1      55.419178       1     156    85.0    140     90            3     1
2      51.663014       1     165    64.0    130     70            3     1
3      48.282192       2     169    82.0    150    100            1     1
4      47.873973       1     156    56.0    100     60            1     1
...          ...     ...     ...     ...    ...    ...          ...   ...
69995  52.712329       2     168    76.0    120     80            1     1
69996  61.920548       1     158   126.0    140     90            2     2
69997  52.235616       2     183   105.0    180     90            3     1
69998  61.454795       1     163    72.0    135     80            1     2
69999  56.273973       1     170    72.0    120     80            2     1

       smoke  alco  phy_activity  cardio
0          0     0             1       0
1          0     0             1       1
2          0     0             0       1
3          0     0             1       1
4          0     0             0       0
...      ...   ...           ...     ...
69995      1     0             1       0
69996      0     0             1       1
69997      0     1             0       1
69998      0     0             0       1
69999      0     0             1       0

[68087 rows x 12 columns]

In [ ]:
'''cols = list(d.columns)

# remove bmi and cardio
cols.remove('bmi')
cols.remove('cardio')

# add bmi and then cardio at end
cols = cols + ['bmi', 'cardio']

# reorder dataframe
d = d[cols]'''
#to add the column bmi right before the target column

In [68]:
d.to_csv("cleaned_data.csv", index=False)